//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildArmsRandomizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WildArmsRandomizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0]
        ///|ATP|
        ///40-Gella Eater!
        ///191-Banishing Buster Anchor!
        ///|SOR|
        ///|EFF|
        ///10-Flash!
        ///24-Flash
        ///[1]
        ///|ATP|
        ///130-Esperanza!
        ///133-Asrael!
        ///138-Doom Bringer!
        ///152-Glumzamber!
        ///166-Blade Lance!
        ///177-Land Master!
        ///178-Trident!
        ///185-Black Hole Bullet!
        ///193-Mantis Fist!
        ///210-Evil Sword Luceid!
        ///20-2 Hit Combo!
        ///90-I hate you!
        ///125-Disrupting Flail!
        ///146-Crescent Fang!
        ///147-Black Fang!
        ///|SOR|
        ///16-Break
        ///21-Freeze
        ///26-Flame
        ///31-Vortex
        ///|EFF|
        ///8-Poison!
        ///5-Heal
        ///[2]
        ///|ATP|
        ///182-Megid Flame!
        ///|SOR|
        ///25-Blast
        ///29-Spark
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AttackTierList {
            get {
                return ResourceManager.GetString("AttackTierList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0]
        ///188 - Berry Cave
        ///189 - Sealed Library
        ///183 - Lolithia&apos;s Tomb
        ///185 - Mount Zenom
        ///181 - Cage Tower
        ///186 - Maze Of Death
        ///219 - Sweet Candy
        ///184 - Pleasing Garden
        ///190 - Cpt Gheist
        ///[1]
        ///220 - Volcannon Trap
        ///218 - Volcannon Trap
        ///178 - Tripillar
        ///180 - Sacred Shrine
        ///215 - Sacred Shrine
        ///193 - Photosphere
        ///203 - Photosphere
        ///205 - Dragon Shrine
        ///206 - Demon&apos;s Lab
        ///[2]
        ///194 - Gate Generator
        ///200 - Gate Generator
        ///179 - Gemini&apos;s Corpse
        ///182 - Pandemonium
        ///191 - Pandemonium
        ///175 - Pandemonium
        ///216 - Ka Di [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BossOrbGroups {
            get {
                return ResourceManager.GetString("BossOrbGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1,0]
        ///188-Zombie
        ///189-Nelgaul
        ///[2,0.5]
        ///183-Magtortous
        ///217-Belselk
        ///[3,0.2]
        ///185-Orga Widow
        ///[4,0.1]
        ///181-Night Gaunt
        ///186-Chaos
        ///219-Zed
        ///[5,0.1]
        ///184-Gigmantis
        ///190-Cpt Gheist
        ///[6,0.2]
        ///220-Zed II
        ///218-Belselk II
        ///178-Mage Fox
        ///[7,0.1]
        ///180-Agaless
        ///215-Alhazad
        ///[8,0.1]
        ///193-Lolithia
        ///203-Mother
        ///205-Harken I
        ///[9,0.3]
        ///206-Harken II
        ///[10,0.2]
        ///194-Diablo
        ///200-Zeikfried
        ///[11,0.1]
        ///179-Mech Drake
        ///182-Turask
        ///[12,0.2]
        ///191-Demon Prophet
        ///175-Shazam
        ///[13,0.1]
        ///216-Alhazad II
        ///[14,0.1]
        ///[15,0.2]
        ///201-Zeikfr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BossTierList {
            get {
                return ResourceManager.GetString("BossTierList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0]
        ///6-Antidote
        ///7-Medicine
        ///8-Violet Rose
        ///9-Heat Salve
        ///10-Pin Wheel
        ///11-Toy Hammer
        ///12-Holy Symbol
        ///13-Light Shroom
        ///240-Small Flower
        ///[1]
        ///28-Power Apple
        ///29-Hardy Apple
        ///30-Mystic Apple
        ///31-Agile Apple
        ///36-Long Knife
        ///48-Arctic Blade
        ///60-Mage Staff
        ///127-Travel Vest
        ///139-Old Cape
        ///151-Breeze Cape
        ///163-Bandanna
        ///169-Cowboy Hat
        ///175-Capuche
        ///[2]
        ///0-Heal Berry
        ///37-Long Sword
        ///49-Chrome Blade
        ///61-Magical Rod
        ///128-Hard Cloak
        ///140-War Coat
        ///152-White Robe
        ///112-Hide Glove
        ///106-Buckler
        ///[3]
        ///38-Bastard Sword
        ///5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemTierList {
            get {
                return ResourceManager.GetString("ItemTierList", resourceCulture);
            }
        }
    }
}
