//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildArmsModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WildArmsModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filgaia
        ///Elw World
        ///Surf Village
        ///Curan Abbey
        ///Adlehyde
        ///Adlehyde Fair
        ///Adlehyde Castle
        ///Milama Village
        ///Baskar Village
        ///Port Timney
        ///Timney Harbor
        ///Saint Centaur
        ///Ship Graveyard
        ///Rosetta Town
        ///Court Seim
        ///Tarjon Village
        ///Vassim&apos;s Lab
        ///Ancient Arena
        ///Elw Pyramid
        ///Sealed Library
        ///Curan Abbey
        ///Isolated Guild
        ///Isolated Guild II
        ///Adlehyde II
        ///Forest Mound
        ///Forest Mound II
        ///Graveyard Docks
        ///Adlehyde III
        ///Adlehyde Castle II
        ///Adlehyde IV
        ///Adlehyde V
        ///Adlehyde VI
        ///Adlehyde VII
        ///Adlehyde VIII
        ///Sacred Shrine
        ///Berry C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AreaNames {
            get {
                return ResourceManager.GetString("AreaNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand Cannon
        ///Prism Ray
        ///Rocket Launcher
        ///Twin Orbs
        ///Bazooka
        ///Phaser
        ///Wild Bunch
        ///Arch Smash.
        /// </summary>
        internal static string ArmNames {
            get {
                return ResourceManager.GetString("ArmNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield
        ///Brutal Attack!
        ///Powerful Blow!
        ///Brutal Blow!
        ///Revive
        ///Heal
        ///Paralysis!
        ///Confusion!
        ///Poison!
        ///Silence!
        ///Flash!
        ///Unregistered.
        ///Reflect
        ///0 is watching.
        ///Body Power Steal!
        ///Pickpocket!
        ///Break
        ///Arm. Down
        ///Slow Down
        ///Sleep
        ///2 Hit Combo!
        ///Freeze
        ///Dispell
        ///Prison
        ///Flash
        ///Blast
        ///Flame
        ///Confusion
        ///Valkyrie
        ///Spark
        ///Silence
        ///Vortex
        ///Hi-Shield
        ///Random Hit!
        ///Guard!
        ///Gella Eater!
        ///Hi-Revive
        ///Hi-Heal
        ///Remedy
        ///Restore
        ///Gella Eater!
        ///Anti Magic
        ///Cut Down!
        ///Rage Attack!
        ///Hi-Reflect
        ///Fire Breath!
        ///Blizzard Breath!
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AttackNames {
            get {
                return ResourceManager.GetString("AttackNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gagison
        ///Flurity
        ///Dekarabia
        ///Dan Tarian
        ///Haborim
        ///Amon
        ///Mechsquito
        ///Bellzebob
        ///Ukoback
        ///Frauloss
        ///Ose
        ///Aipeloss
        ///Alfase
        ///Hell Hound
        ///Garum
        ///Marcokias
        ///Niebass
        ///Bafomet
        ///Balloon
        ///Evil Dead
        ///Rat Monkey
        ///Ghoul
        ///Vampire
        ///Wizard
        ///Nosferatu
        ///Scarecrow
        ///Ripper
        ///Minion
        ///Stoker
        ///Screamer
        ///Galgancher
        ///Wiseman
        ///Racheal
        ///Christine
        ///Durahan
        ///Ghostrider
        ///Tiny Edge
        ///Miann
        ///Sphinx
        ///Kelbim
        ///Nemesis
        ///Devonova
        ///Minatous
        ///Crawly
        ///Wyvern
        ///Hell Diver
        ///Harpy
        ///Siren
        ///Valkyrie
        ///Gallowbear
        ///Snatcher
        ///Venom Bear
        ///Bloodhorn
        ///Gamizine        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EnemyNames {
            get {
                return ResourceManager.GetString("EnemyNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psycho Crack
        ///Sonic Buster
        ///Meteor Dive
        ///Trickster
        ///Heal Blade
        ///Divide Shot
        ///Blast Charge
        ///Slash Rave
        ///Soul Breaker
        ///Guilty Blade
        ///Magnum Fang
        ///Shadow Bind
        ///Phazer Zapp
        ///Cosmic Nova
        ///Void
        ///Trump Card
        ///????
        ///Dark Sweep.
        /// </summary>
        internal static string FastDrawNames {
            get {
                return ResourceManager.GetString("FastDrawNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal Berry
        ///Potion Berry
        ///Mega Berry
        ///Magic Carrot
        ///Revive Fruit
        ///Full Revive
        ///Antidote
        ///Medicine
        ///Violet Rose
        ///Heat Salve
        ///Pin Wheel
        ///Toy Hammer
        ///Holy Symbol
        ///Light Shroom
        ///ÿ
        ///Nectar
        ///Ambrosia
        ///ÿDiary
        ///ÿSheriff Whop
        ///Black Pass
        ///Magic Map
        ///1 Gella Coin
        ///ÿ
        ///ÿ
        ///Bone
        ///Bullet Clip
        ///Secret Sign
        ///Crest Graph
        ///Power Apple
        ///Hardy Apple
        ///Mystic Apple
        ///Agile Apple
        ///Duplicator
        ///Lucky Card
        ///ÿ
        ///ÿ
        ///Long Knife
        ///Long Sword
        ///Bastard Sword
        ///Claymore
        ///Bronze Sword
        ///Cross Saber
        ///Night Fencer
        ///Hybri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ItemNames {
            get {
                return ResourceManager.GetString("ItemNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield
        ///Protect
        ///Suction
        ///Hide
        ///Revive
        ///Heal
        ///Awaken
        ///Field
        ///Curse
        ///Dark Blow
        ///Light Blow
        ///Rage
        ///Reflect
        ///Air Screen
        ///Escape
        ///Quick
        ///Break
        ///Arm Down
        ///Slow Down
        ///Sleep
        ///Analyze
        ///Freeze
        ///Dispell
        ///Prison
        ///Flash
        ///Blast
        ///Flame
        ///Confusion
        ///Valkyrie
        ///Spark
        ///Silence
        ///Vortex
        ///Hi-Shield
        ///Life Guard
        ///Hyper
        ///Invisible
        ///Hi-Revive
        ///Hi-Heal
        ///Remedy
        ///Restore
        ///Counter Up
        ///Anti-Magic
        ///Bomb
        ///Soul Guard
        ///Hi-Reflect
        ///Lock State
        ///Dummy Doll
        ///Teleport
        ///Hi-Break
        ///Saint
        ///Eraser
        ///Life Drain
        ///Banish
        ///Hi-Freeze
        ///Randomizer
        ///Hi-Prison        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SpellNames {
            get {
                return ResourceManager.GetString("SpellNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gurdijeff
        ///Stoldark
        ///Moa Gault
        ///Fengalon
        ///Nua Shakks
        ///Denogenos
        ///Stare Roe
        ///Ge Ramtos
        ///Lucadia
        ///Ione Paua
        ///Solus Emsu
        ///Aru Sulato
        ///Dan Dairam
        ///Rigdobrite
        ///Equitess
        ///Zeldukes
        ///Odoryuk
        ///Duras Drum
        ///Raftina
        ///Justine
        ///Zephyr
        ///Gurdijeff
        ///Stoldark
        ///Moa Gault
        ///Fengalon
        ///Nua Shakks
        ///Denogenos
        ///Stare Roe
        ///Ge Ramtos
        ///Lucadia
        ///Ione Paua
        ///Solus Emsu
        ///Aru Sulato
        ///Dan Dairam
        ///Rigdobrite
        ///Equitess
        ///Zeldukes
        ///Odoryuk
        ///Duras Drum
        ///Raftina
        ///Justine
        ///Zephyr.
        /// </summary>
        internal static string SummonNames {
            get {
                return ResourceManager.GetString("SummonNames", resourceCulture);
            }
        }
    }
}
